---
- name: Provision test
  hosts: all

  tasks:
    - name: Print host information
      debug:
        msg: "{{ ansible_fqdn }}: {{ ansible_distribution }} {{ ansible_distribution_version}}"

    - name: Checkout shared playbooks repo
      git:
        repo: "https://github.com/cheretbe/ansible-playbooks.git"
        dest: "/opt/ansible-playbooks"
      become: true

- name: Test me
  import_playbook: /opt/ansible-playbooks/linux_server_setup.yml
