---
- name: Setup common parameters
  import_playbook: /opt/ansible-playbooks/linux_server_setup.yml

- name: OpenVPN server provision
  hosts: all

  tasks:
    - include_role: name="/opt/ansible-playbooks/ovpn-server"

    - name: Update facts to make ansible_tun0 variable available
      setup:

    - include_role: name="/opt/ansible-playbooks/router"
