---
- name: OpenVPN server provision
  hosts: all

  tasks:
    - name: Print host information
      debug:
        msg: "{{ ansible_fqdn }}: {{ ansible_distribution }} {{ ansible_distribution_version}}"

- name: Setup common parameters
  import_playbook: /opt/ansible-playbooks/linux_server_setup.yml
